version: '3.9'
services:

  flask-app:
    container_name: 'flask-python-application'
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      MYSQL_HOST: 'mysql-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB: 'devops'
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    container_name: 'mysql-db'
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'devops'
    volumes:
      - type: volume
        source: mysql-volume-data
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-volume-data:
